//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KargazImalatTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAGLANTI_ELEMANLARI_CELIK
    {
        public int MSLINK { get; set; }
        public Nullable<int> MAPID { get; set; }
        public string CINSI { get; set; }
        public string TIPI { get; set; }
        public string CAP { get; set; }
        public string SEBEKE_ELEMANI_MI { get; set; }
        public string YATIRIMYILI { get; set; }
        public string MUTEAHHITADI { get; set; }
        public Nullable<System.DateTime> IMALATTARIHI { get; set; }
        public string FORMNO { get; set; }
        public string VARLIK_KODU { get; set; }
        public string EKIPNO { get; set; }
        public string MARKA { get; set; }
        public Nullable<double> FORM_METRAJ { get; set; }
        public Nullable<double> ASBUILT_METRAJ { get; set; }
        public string HATNO { get; set; }
        public string KAPLAMA_TIPI { get; set; }
        public string FROM_ID { get; set; }
        public Nullable<int> FROM_MSLINK { get; set; }
        public string TO_ID { get; set; }
        public Nullable<int> TO_MSLINK { get; set; }
        public Nullable<short> YERI { get; set; }
        public Nullable<double> DERINLIK { get; set; }
        public Nullable<double> KONUM_X_KOOR { get; set; }
        public Nullable<double> KONUM_Y_KOOR { get; set; }
        public string SEKTOR { get; set; }
        public string GIRIS_BASINCI { get; set; }
        public string ISLETME_BASINCI { get; set; }
        public Nullable<System.DateTime> SIZINTI_INCELEME_SON_TARIH { get; set; }
        public Nullable<int> SIZINTI_INCELEME_ARALIGI { get; set; }
        public Nullable<System.DateTime> TEST_TARIHI { get; set; }
        public string TEST_SURESI { get; set; }
        public string TEST_BASINCI { get; set; }
        public string DURUM { get; set; }
        public Nullable<System.DateTime> GAZLANMA_TARIHI { get; set; }
        public Nullable<decimal> YOL_MSLINK { get; set; }
        public Nullable<int> IL_KODU { get; set; }
        public Nullable<int> ILCE_KODU { get; set; }
        public string MAHALLE_KODU { get; set; }
        public Nullable<double> KULLANILAN_ACI { get; set; }
        public Nullable<short> HAKEDISE_DAHIL { get; set; }
        public Nullable<decimal> FORM_METRAJ_TEE_KISA_KOL { get; set; }
    }
}
