//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KargazImalatTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAGLANTI_ELEMANLARI_PE
    {
        public int MSLINK { get; set; }
        public Nullable<int> MAPID { get; set; }
        public string TIPI { get; set; }
        public string CAP { get; set; }
        public string CINSI { get; set; }
        public string SEBEKE_ELEMANI_MI { get; set; }
        public Nullable<System.DateTime> GAZLANMA_TARIHI { get; set; }
        public Nullable<int> SERVIS_ID { get; set; }
        public Nullable<double> DERINLIK { get; set; }
        public Nullable<decimal> HAT_MSLINK { get; set; }
        public Nullable<int> ACIL_SISTEM_OBJE_ID { get; set; }
        public string ACIL_SISTEM_DURUM_TANIMI { get; set; }
        public Nullable<double> KONUM_X_KOOR { get; set; }
        public Nullable<double> KONUM_Y_KOOR { get; set; }
        public string KONUM_TESPIT_SEKLI { get; set; }
        public Nullable<double> KONUM_MESAFE { get; set; }
        public string MALZEME_DURUM { get; set; }
        public string BOLGE { get; set; }
        public string SEKTOR { get; set; }
        public string URETICI_FIRMA { get; set; }
        public string VARLIK_KODU { get; set; }
        public Nullable<int> WORKORDERID { get; set; }
        public string DURUM { get; set; }
        public string YATIRIMYILI { get; set; }
        public string MARKAMODEL { get; set; }
        public string MUTEAHHITADI { get; set; }
        public string TEDARIKCIFIRMA { get; set; }
        public Nullable<System.DateTime> IMALATTARIHI { get; set; }
        public Nullable<decimal> YOL_MSLINK { get; set; }
        public Nullable<int> IL_KODU { get; set; }
        public Nullable<int> ILCE_KODU { get; set; }
        public string FORMNO { get; set; }
        public string MAHALLE_KODU { get; set; }
        public string FUZYON { get; set; }
        public string EKIPNO { get; set; }
        public string KAYNAKCI1 { get; set; }
        public string KAYNAKCI2 { get; set; }
        public string GIRIS_BASINCI { get; set; }
        public string ISLETME_BASINCI { get; set; }
        public Nullable<System.DateTime> TEST_TARIHI { get; set; }
        public string TEST_SURESI { get; set; }
        public string TEST_BASINCI { get; set; }
        public Nullable<System.DateTime> SIZINTI_INCELEME_SON_TARIH { get; set; }
        public Nullable<int> SIZINTI_INCELEME_ARALIGI { get; set; }
        public Nullable<double> KULLANILAN_ACI { get; set; }
        public Nullable<short> HAKEDISE_DAHIL { get; set; }
    }
}
