//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KargazImalatTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class bina
    {
        public Nullable<int> mslink { get; set; }
        public Nullable<int> mapid { get; set; }
        public int bina_kodu { get; set; }
        public string bina_adi { get; set; }
        public Nullable<int> yol_kodu { get; set; }
        public string adres_kodu { get; set; }
        public string dis_kapi_no { get; set; }
        public Nullable<int> kat_adedi { get; set; }
        public Nullable<int> daire_sayisi { get; set; }
        public Nullable<int> isyeri_sayisi { get; set; }
        public string isinma_sekli { get; set; }
        public Nullable<double> kazan_kap { get; set; }
        public Nullable<int> servis_kutusu_mslink { get; set; }
        public string blok_adi { get; set; }
        public string mahalle_kodu { get; set; }
        public string ilce_kodu { get; set; }
        public Nullable<double> alan { get; set; }
        public string sektor { get; set; }
        public string kullanim_tipi { get; set; }
        public string il_kodu { get; set; }
    }
}
