using DevExpress.XtraGrid.Views.Grid;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace KargazImalatTakip
{
    public partial class FrmPeHatRaporu : Form
    {
        public FrmPeHatRaporu()
        {
            InitializeComponent();
        }

        private void BtnExcelAktar_Click(object sender, EventArgs e)
        {
            SaveFileDialog kayit = new SaveFileDialog();
            kayit.FileName = DateTime.Now.Day + "." + DateTime.Now.Month + "." + DateTime.Now.Year + " - Yol Kazı raporu";
            if (kayit.ShowDialog() == DialogResult.OK)
            {
                gridView1.ExportToXlsx(kayit.FileName + ".xlsx");
            }
        }

        void listele()
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource2.Fill();
        }

        void detayListe()
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void BtnListele_Click(object sender, EventArgs e)
        {
            listele();
        }

        private void BtnGrupListele_Click(object sender, EventArgs e)
        {
            detayListe();
        }

        private void gridView3_RowCellStyle(object sender, RowCellStyleEventArgs e)
        {
            //if (e.RowHandle >= 0)
            //{
            //    GridView fark = sender as GridView;
            //    if(e.Column.FieldName == "FARK")
            //    {
            //        decimal yolKazi = Convert.ToDecimal(fark.GetRowCellDisplayText(e.RowHandle, fark.Columns[5]));
            //        if (yolKazi<0)
            //            e.Appearance.BackColor = Color.Red;
                   
            //    }
            //}
        }
    }
}
