//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KargazImalatTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class HATLAR
    {
        public int MSLINK { get; set; }
        public Nullable<int> MAPID { get; set; }
        public string MALZEME_CINSI { get; set; }
        public string NET_BORU_CAPI { get; set; }
        public Nullable<int> GAZ_AKIS_YONU { get; set; }
        public string FROM_ID { get; set; }
        public Nullable<int> FROM_MSLINK { get; set; }
        public string TO_ID { get; set; }
        public Nullable<int> TO_MSLINK { get; set; }
        public string VERI_KAYNAGI { get; set; }
        public string DURUM { get; set; }
        public Nullable<System.DateTime> IMALAT_TARIHI { get; set; }
        public Nullable<System.DateTime> GAZLANMA_TARIHI { get; set; }
        public string SEKTOR { get; set; }
        public string KAPLAMA_TIPI { get; set; }
        public string SISTEM_GIRIS_BASINCI { get; set; }
        public string SISTEM_STANDART_BASINCI { get; set; }
        public Nullable<double> SISTEM_BASINC_ARALIGI { get; set; }
        public string SISTEM_STANDART_BASINC_BIRIMI { get; set; }
        public Nullable<int> ACIL_SISTEM_OBJE_ID { get; set; }
        public string ACIL_SISTEM_DURUM_TANIMI { get; set; }
        public Nullable<System.DateTime> SIZINTI_INCELEME_SON_TARIH { get; set; }
        public Nullable<int> SIZINTI_INCELEME_ARALIGI { get; set; }
        public string MARKA { get; set; }
        public Nullable<double> BORU_UZUNLUGU { get; set; }
        public Nullable<double> ASBUILT_METRAJ { get; set; }
        public Nullable<System.DateTime> BORU_SON_TEST_TARIHI { get; set; }
        public string BORU_SON_TEST_SURESI { get; set; }
        public string BORU_SON_TEST_BASINCI { get; set; }
        public string VARLIK_KODU { get; set; }
        public Nullable<int> WORKORDERID { get; set; }
        public string YATIRIMYILI { get; set; }
        public string MUTEAHHITADI { get; set; }
        public string TEDARIKCIFIRMA { get; set; }
        public Nullable<decimal> REGULATOR_MSLINK { get; set; }
        public Nullable<decimal> YOL_MSLINK { get; set; }
        public Nullable<int> IL_KODU { get; set; }
        public Nullable<int> ILCE_KODU { get; set; }
        public string FORMNO { get; set; }
        public string LOT { get; set; }
        public string MAHALLE_KODU { get; set; }
        public string EKIPNO { get; set; }
        public string HATNO { get; set; }
        public Nullable<short> YERI { get; set; }
        public Nullable<short> HAKEDISE_DAHIL { get; set; }
        public Nullable<double> YATAY_ASBUILT_METRAJ { get; set; }
        public string KAZI_RUHSATNO { get; set; }
        public Nullable<double> KAZI_BOYU { get; set; }
    }
}
