//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KargazImalatTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVIS_KUTUSU
    {
        public int MSLINK { get; set; }
        public Nullable<int> MAPID { get; set; }
        public string KUTU_TIPI { get; set; }
        public string CINSI { get; set; }
        public Nullable<int> YOL_MSLINK { get; set; }
        public Nullable<int> AKTIF { get; set; }
        public string DURUM { get; set; }
        public string KUTU_MARKASI { get; set; }
        public string REG_NO { get; set; }
        public Nullable<double> REG_TUKETIM { get; set; }
        public string REG_BASINC { get; set; }
        public string REG_KUTUTIPI { get; set; }
        public string REG_KAPASITE { get; set; }
        public Nullable<System.DateTime> REG_MONTAJTARIHI { get; set; }
        public string REG_KULLANIMTURU { get; set; }
        public string REG_TIPI { get; set; }
        public string REG_MARKASI { get; set; }
        public Nullable<int> REG_ADEDI { get; set; }
        public string VARLIK_KODU { get; set; }
        public Nullable<int> WORKORDERID { get; set; }
        public string YATIRIMYILI { get; set; }
        public string KUTU_NO { get; set; }
        public string SKUTUVANASI { get; set; }
        public string SKUTUVANAMARKASI { get; set; }
        public string CIKISBASINCI { get; set; }
        public Nullable<System.DateTime> IMALATTARIHI { get; set; }
        public string MUTEAHHITADI { get; set; }
        public string TEDARIKCIFIRMAREG { get; set; }
        public Nullable<long> HAT_MSLINK { get; set; }
        public Nullable<int> IL_KODU { get; set; }
        public Nullable<int> ILCE_KODU { get; set; }
        public string FORMNO { get; set; }
        public string MAHALLE_KODU { get; set; }
        public Nullable<short> HAKEDISE_DAHIL { get; set; }
        public string KUTU_YERI { get; set; }
    }
}
