//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KargazImalatTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVIS_HATLARI
    {
        public int MSLINK { get; set; }
        public Nullable<int> MAPID { get; set; }
        public string TIPI { get; set; }
        public string CAP { get; set; }
        public string FROM_ID { get; set; }
        public Nullable<int> FROM_MSLINK { get; set; }
        public string TO_ID { get; set; }
        public Nullable<int> TO_MSLINK { get; set; }
        public string VARLIK_KODU { get; set; }
        public Nullable<int> WORKORDERID { get; set; }
        public string DURUM { get; set; }
        public string YATIRIMYILI { get; set; }
        public Nullable<decimal> REGULATOR_MSLINK { get; set; }
        public string SEKTOR { get; set; }
        public Nullable<double> SHATTIMETRAJ { get; set; }
        public Nullable<System.DateTime> IMALATTARIHI { get; set; }
        public string MUTEAHHITADI { get; set; }
        public string MARKAMODEL { get; set; }
        public string LOTNO { get; set; }
        public Nullable<long> HAT_MSLINK { get; set; }
        public Nullable<long> YOL_MSLINK { get; set; }
        public Nullable<int> IL_KODU { get; set; }
        public Nullable<int> ILCE_KODU { get; set; }
        public string FORMNO { get; set; }
        public string MAHALLE_KODU { get; set; }
        public string EKIPNO { get; set; }
        public Nullable<double> KAZIBOYU { get; set; }
        public Nullable<double> BORUBOYU { get; set; }
        public Nullable<double> ASFALTBOYU { get; set; }
        public string YUZEYKAPLAMA { get; set; }
        public Nullable<short> HAKEDISE_DAHIL { get; set; }
        public Nullable<double> YATAY_ASBUILT_METRAJ { get; set; }
        public Nullable<double> ASFALT { get; set; }
    }
}
