//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KargazImalatTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVIS_ELEMANLARI
    {
        public int MSLINK { get; set; }
        public Nullable<int> MAPID { get; set; }
        public string TIPI { get; set; }
        public string CAP { get; set; }
        public string CINSI { get; set; }
        public Nullable<double> DERINLIK { get; set; }
        public Nullable<long> HAT_MSLINK { get; set; }
        public Nullable<double> KONUM_X_KOOR { get; set; }
        public Nullable<double> KONUM_Y_KOOR { get; set; }
        public string KONUM_TESPIT_SEKLI { get; set; }
        public Nullable<double> KONUM_MESAFE { get; set; }
        public string BOLGE { get; set; }
        public string SEKTOR { get; set; }
        public string VARLIK_KODU { get; set; }
        public Nullable<int> WORKORDERID { get; set; }
        public string DURUM { get; set; }
        public string MALZEME_DURUM { get; set; }
        public string YATIRIMYILI { get; set; }
        public string MARKAMODEL { get; set; }
        public string MUTEAHHITADI { get; set; }
        public string FORMNO { get; set; }
        public Nullable<long> YOL_MSLINK { get; set; }
        public Nullable<int> IL_KODU { get; set; }
        public Nullable<int> ILCE_KODU { get; set; }
        public string MAHALLE_KODU { get; set; }
        public Nullable<System.DateTime> IMALAT_TARIHI { get; set; }
        public string GAZ_STOP { get; set; }
        public Nullable<short> HAKEDISE_DAHIL { get; set; }
    }
}
