//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KargazImalatTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tesisat
    {
        public int TesisatKod { get; set; }
        public Nullable<int> BinaKod { get; set; }
        public string DaireNo { get; set; }
        public string SiteAdi { get; set; }
        public string BinaAdi { get; set; }
        public string EskiAdreskodu { get; set; }
        public string EskiGazAboneNo { get; set; }
        public string SayacNo { get; set; }
        public Nullable<long> BasvuruKod { get; set; }
        public Nullable<long> SozlesmeKod { get; set; }
        public Nullable<long> BasvuruTuketiciKod { get; set; }
        public Nullable<long> SozlesmeTuketiciKod { get; set; }
        public string TarifeTipKod { get; set; }
        public string TesisatDurumKod { get; set; }
        public int Alan { get; set; }
        public string SayacTur { get; set; }
        public string SayacTipKod { get; set; }
        public Nullable<int> SayacBasinc { get; set; }
        public decimal SayacDebi { get; set; }
        public int ProjeAlanM2 { get; set; }
        public int BBS { get; set; }
        public string Bilgi { get; set; }
        public Nullable<int> ProjeBirimAlan { get; set; }
    }
}
