//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KargazImalatTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class VANA
    {
        public int MSLINK { get; set; }
        public Nullable<int> MAPID { get; set; }
        public string VANA_TIPI { get; set; }
        public string CAP { get; set; }
        public string MALZEME_CINSI { get; set; }
        public string VANA_NO { get; set; }
        public string VANA_ISLETME_DURUMU { get; set; }
        public string BASINC { get; set; }
        public string KAPATMA_YONU { get; set; }
        public string KAPATMA_TURU { get; set; }
        public Nullable<double> DERINLIK { get; set; }
        public Nullable<long> HAT_MSLINK { get; set; }
        public Nullable<long> ACIL_SISTEM_OBJE_ID { get; set; }
        public string ACIL_SISTEM_DURUM_TANIMI { get; set; }
        public Nullable<double> KONUM_X_KOOR { get; set; }
        public Nullable<double> KONUM_Y_KOOR { get; set; }
        public string KONUM_TESPIT_SEKLI { get; set; }
        public Nullable<double> KONUM_MESAFE { get; set; }
        public string MALZEME_DURUM { get; set; }
        public string VANA_ADRES { get; set; }
        public Nullable<System.DateTime> URETIM_YILI { get; set; }
        public string SERI_NO { get; set; }
        public string BOLGE { get; set; }
        public string SEKTOR { get; set; }
        public string URETICI_FIRMA { get; set; }
        public Nullable<System.DateTime> GAZLANMA_TARIHI { get; set; }
        public Nullable<int> SERVIS_ID { get; set; }
        public string VARLIK_KODU { get; set; }
        public Nullable<int> WORKORDERID { get; set; }
        public string DURUM { get; set; }
        public Nullable<int> BAKIM_PERIYODU { get; set; }
        public string YATIRIMYILI { get; set; }
        public string MUTEAHHITADI { get; set; }
        public string TEDARIKCIFIRMA { get; set; }
        public string MARKA { get; set; }
        public Nullable<long> YOL_MSLINK { get; set; }
        public Nullable<int> IL_KODU { get; set; }
        public Nullable<int> ILCE_KODU { get; set; }
        public string FORMNO { get; set; }
        public string MAHALLE_KODU { get; set; }
        public Nullable<System.DateTime> IMALAT_TARIHI { get; set; }
        public string KAIDE { get; set; }
        public Nullable<int> TUR_SAYISI { get; set; }
        public Nullable<double> ASBUILT_METRAJ { get; set; }
        public Nullable<short> HAKEDISE_DAHIL { get; set; }
        public string BLOFCAP1 { get; set; }
        public string BLOFCAP2 { get; set; }
        public string BLOFSERINO1 { get; set; }
        public string BLOFSERINO2 { get; set; }
    }
}
